package pepperTap;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import pepperTap.Cart;
import pepperTap.LineItem;

import pepperTap.CartDao;
import pepperTap.LineItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartDaoConfig;
    private final DaoConfig lineItemDaoConfig;

    private final CartDao cartDao;
    private final LineItemDao lineItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartDaoConfig = daoConfigMap.get(CartDao.class).clone();
        cartDaoConfig.initIdentityScope(type);

        lineItemDaoConfig = daoConfigMap.get(LineItemDao.class).clone();
        lineItemDaoConfig.initIdentityScope(type);

        cartDao = new CartDao(cartDaoConfig, this);
        lineItemDao = new LineItemDao(lineItemDaoConfig, this);

        registerDao(Cart.class, cartDao);
        registerDao(LineItem.class, lineItemDao);
    }
    
    public void clear() {
        cartDaoConfig.getIdentityScope().clear();
        lineItemDaoConfig.getIdentityScope().clear();
    }

    public CartDao getCartDao() {
        return cartDao;
    }

    public LineItemDao getLineItemDao() {
        return lineItemDao;
    }

}
