package pepperTap;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LINE_ITEM.
 */
public class LineItem {

    private Long id;
    private String product_code;
    private String title;
    private Float mrp;
    private Float sale_price;
    private Integer quantity;
    private Integer max_limit;
    private Long classification_id;
    private String offer;
    private Float discount;
    private String image_url;
    private Float total;
    private String display_attribute;
    private String discount_string;
    private String classifications;
    private Long cartID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LineItem() {
    }

    public LineItem(Long id) {
        this.id = id;
    }

    public LineItem(Long id, String product_code, String title, Float mrp, Float sale_price, Integer quantity, Integer max_limit, Long classification_id, String offer, Float discount, String image_url, Float total, String display_attribute, String discount_string, String classifications, Long cartID) {
        this.id = id;
        this.product_code = product_code;
        this.title = title;
        this.mrp = mrp;
        this.sale_price = sale_price;
        this.quantity = quantity;
        this.max_limit = max_limit;
        this.classification_id = classification_id;
        this.offer = offer;
        this.discount = discount;
        this.image_url = image_url;
        this.total = total;
        this.display_attribute = display_attribute;
        this.discount_string = discount_string;
        this.classifications = classifications;
        this.cartID = cartID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProduct_code() {
        return product_code;
    }

    public void setProduct_code(String product_code) {
        this.product_code = product_code;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Float getMrp() {
        return mrp;
    }

    public void setMrp(Float mrp) {
        this.mrp = mrp;
    }

    public Float getSale_price() {
        return sale_price;
    }

    public void setSale_price(Float sale_price) {
        this.sale_price = sale_price;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Integer getMax_limit() {
        return max_limit;
    }

    public void setMax_limit(Integer max_limit) {
        this.max_limit = max_limit;
    }

    public Long getClassification_id() {
        return classification_id;
    }

    public void setClassification_id(Long classification_id) {
        this.classification_id = classification_id;
    }

    public String getOffer() {
        return offer;
    }

    public void setOffer(String offer) {
        this.offer = offer;
    }

    public Float getDiscount() {
        return discount;
    }

    public void setDiscount(Float discount) {
        this.discount = discount;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public Float getTotal() {
        return total;
    }

    public void setTotal(Float total) {
        this.total = total;
    }

    public String getDisplay_attribute() {
        return display_attribute;
    }

    public void setDisplay_attribute(String display_attribute) {
        this.display_attribute = display_attribute;
    }

    public String getDiscount_string() {
        return discount_string;
    }

    public void setDiscount_string(String discount_string) {
        this.discount_string = discount_string;
    }

    public String getClassifications() {
        return classifications;
    }

    public void setClassifications(String classifications) {
        this.classifications = classifications;
    }

    public Long getCartID() {
        return cartID;
    }

    public void setCartID(Long cartID) {
        this.cartID = cartID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
